#!/bin/bash
# Distill ALLaVA responses with the ~122B verifier (Qwen3.5-122B-A10B), for MTP
# training. MTP fine-tunes the verifier's own head to predict ITS OWN
# continuations, so the training targets must be generated by THIS model — not the
# 9B's distill and not the ground-truth ALLaVA answers.
#
# Generation only (no trainer), so the verifier gets ALL 8 GPUs via tensor-parallel.
# Wraps examples/train/distill_allava_qwen35_10k.sh (fully parametric) with 122B
# settings.
#
# USAGE
#   MODEL=/data/wenxuan/Qwen3.5-122B-A10B MAX_SAMPLES=10000 \
#   bash examples/train/distill_allava_122b.sh
#   # -> data/allava/allava_122b_distill_10k.jsonl  (feed to nohup_mtp_122b_allava_distilled.sh)
#
# heads=32 -> TP must be 4 or 8; TP=8 here (all GPUs, fastest gen, ~30.5 GB/GPU).
# Two unconnected machines? split the range like the 9B 8gpu distill:
#   A: SKIP_SAMPLES=0 MAX_SAMPLES=50000 ; B: SKIP_SAMPLES=50000 MAX_SAMPLES=50000
#   (set OUT_JSONL per machine, then cat the two files together).

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

# ---- 122B verifier + output ----
export MODEL="${MODEL:-/data/wenxuan/Qwen3.5-122B-A10B}"
if [ ! -d "$MODEL" ]; then
    echo "[fatal] MODEL not found: $MODEL  (set MODEL=/path/to/your/122B)"
    exit 1
fi
export ALLAVA_IMAGE_ROOT="${ALLAVA_IMAGE_ROOT:-/data/wenxuan/ALLaVA-4V}"
export MAX_SAMPLES="${MAX_SAMPLES:-10000}"
export OUT_JSONL="${OUT_JSONL:-$REPO_ROOT/data/allava/allava_122b_distill_$(( MAX_SAMPLES / 1000 ))k.jsonl}"

# ---- serve the 122B on all 8 GPUs (generation only -> no trainer to leave room for) ----
export GPUS="${GPUS:-0,1,2,3,4,5,6,7}"
export TP="${TP:-8}"                 # 32 heads / 8 = OK; 244GB / 8 ≈ 30.5 GB/GPU
export PORT="${PORT:-8100}"
export SERVED_MODEL_NAME="${SERVED_MODEL_NAME:-qwen3.5-122b-allava-distill}"
export GPU_MEMORY_UTIL="${GPU_MEMORY_UTIL:-0.90}"
export MAX_MODEL_LEN="${MAX_MODEL_LEN:-8192}"
export MAX_NUM_SEQS="${MAX_NUM_SEQS:-32}"   # tiny KV (2 KV heads) -> push parallelism for throughput
export MAX_TOKENS="${MAX_TOKENS:-512}"
export TEMPERATURE="${TEMPERATURE:-0}"       # greedy: MTP learns the verifier's argmax continuations
export ENFORCE_EAGER="${ENFORCE_EAGER:-1}"
export ATTENTION_BACKEND="${ATTENTION_BACKEND:-flash_attn}"
export DTYPE="${DTYPE:-bfloat16}"
export RESUME="${RESUME:-1}"

echo "=== 122B ALLaVA distillation ==="
echo "  model:       $MODEL"
echo "  serve:       TP=$TP on GPUs [$GPUS]  (mem_util=$GPU_MEMORY_UTIL, max_num_seqs=$MAX_NUM_SEQS)"
echo "  out_jsonl:   $OUT_JSONL"
echo "  max_samples: $MAX_SAMPLES   skip=${SKIP_SAMPLES:-0}   max_tokens=$MAX_TOKENS   temp=$TEMPERATURE"

exec bash examples/train/distill_allava_qwen35_10k.sh
