#!/bin/bash
# STEP 1 (CLIENT) — Data distillation for MTP on the client's SFT'd 122B.
#
# WHY: MTP fine-tunes the verifier's OWN native MTP head to predict ITS OWN
# continuations. After the client's SFT, the target distribution has shifted, so
# the training targets MUST be generated by the *post-SFT* model on *client-domain*
# prompts — not the original 122B, not the 9B distill, and not the ground-truth
# answers. That on-policy alignment is the entire value of re-training the draft.
#
# This wraps the validated examples/train/distill_allava_122b.sh, swapping in:
#   - CLIENT_MODEL        the client's post-SFT 122B weights (verifier)
#   - CLIENT_DATA         client-domain prompts in LLaVA/ALLaVA-style JSON
#   - CLIENT_IMAGE_ROOT   root that the records' `image` paths resolve against
#
# CLIENT DATA FORMAT (consumed by scripts/distill_allava_with_qwen.py):
#   A JSON list (or {"data"/"annotations"/"items"/"records": [...]}) of records:
#     { "image": "<rel-or-abs path>",
#       "conversations": [ {"from":"human","value":"<image>\n<question>"},
#                          {"from":"gpt","value":"<original answer — DROPPED>"} ] }
#   Only the image + first user turn(s) are kept; the GT answer is dropped and
#   regenerated greedily by CLIENT_MODEL. Multiple files: space-separate CLIENT_DATA.
#   (image-key=`image`, conv-key=`conversations`; override via IMAGE_KEY/CONV_KEY.)
#
# USAGE
#   CLIENT_MODEL=/data/wenxuan/Qwen3.5-122B-A10B-sft \
#   CLIENT_DATA="/data/client/domain_train.json" \
#   CLIENT_IMAGE_ROOT=/data/client/images \
#   MAX_SAMPLES=10000 \
#   bash examples/train/distill_client_122b.sh
#   # -> data/client/client_122b_distill_10k.jsonl  (feed to STEP 2)
#
# Two unconnected machines? split the range (like the ALLaVA 8gpu distill):
#   A: SKIP_SAMPLES=0     MAX_SAMPLES=50000 OUT_JSONL=.../client_122b_distill_partA.jsonl
#   B: SKIP_SAMPLES=50000 MAX_SAMPLES=50000 OUT_JSONL=.../client_122b_distill_partB.jsonl
#   then `cat partA partB > client_122b_distill_100k.jsonl`.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

# ---- client knobs (the only three things you must set) ----
CLIENT_MODEL="${CLIENT_MODEL:-/data/wenxuan/Qwen3.5-122B-A10B-sft}"
CLIENT_DATA="${CLIENT_DATA:-}"
CLIENT_IMAGE_ROOT="${CLIENT_IMAGE_ROOT:-/data/client/images}"

if [ ! -d "$CLIENT_MODEL" ]; then
    echo "[fatal] CLIENT_MODEL not found: $CLIENT_MODEL  (set it to the post-SFT 122B path)"
    exit 1
fi
if [ -z "$CLIENT_DATA" ]; then
    echo "[fatal] set CLIENT_DATA=\"/path/to/client_domain.json [more.json ...]\" (LLaVA/ALLaVA-style)"
    exit 1
fi
if [ ! -d "$CLIENT_IMAGE_ROOT" ]; then
    echo "[fatal] CLIENT_IMAGE_ROOT not found: $CLIENT_IMAGE_ROOT"
    exit 1
fi

MAX_SAMPLES="${MAX_SAMPLES:-10000}"

# Map client knobs onto the base distill launcher's contract.
export MODEL="$CLIENT_MODEL"
export ALLAVA_INPUTS="$CLIENT_DATA"
export ALLAVA_IMAGE_ROOT="$CLIENT_IMAGE_ROOT"
export OUT_JSONL="${OUT_JSONL:-$REPO_ROOT/data/client/client_122b_distill_$(( MAX_SAMPLES / 1000 ))k.jsonl}"
export MAX_SAMPLES
export SERVED_MODEL_NAME="${SERVED_MODEL_NAME:-qwen3.5-122b-sft-client-distill}"
mkdir -p "$(dirname "$OUT_JSONL")"

echo "=== STEP 1: client-domain distillation on post-SFT 122B ==="
echo "  client_model:  $MODEL   (post-SFT verifier; generates the targets)"
echo "  client_data:   $CLIENT_DATA"
echo "  image_root:    $ALLAVA_IMAGE_ROOT"
echo "  out_jsonl:     $OUT_JSONL"
echo "  max_samples:   $MAX_SAMPLES   skip=${SKIP_SAMPLES:-0}   temp=${TEMPERATURE:-0} (greedy)"

# distill_allava_122b.sh serves the verifier TP=8 on all 8 GPUs (gen-only) and
# runs scripts/distill_allava_with_qwen.py. All its knobs pass through env.
exec bash "$SCRIPT_DIR/distill_allava_122b.sh"
