#!/bin/bash
# Configurable online MTP finetuning pipeline.
#
# This wraps the native MTP path already supported by scripts/train.py:
#   prepare data -> launch vLLM hidden-state extraction -> train -> stitch
#
# Override any variable below from the environment, for example:
#   MODEL=Qwen/Qwen3.5-0.8B TARGET_LAYER_IDS="24" \
#     bash examples/train/mtp_online_pipeline.sh

set -euo pipefail

# ============ Model and data ============
MODEL="${MODEL:-Qwen/Qwen3.5-9B}"
DATA_PATH="${DATA_PATH:-}"
DATASET_REPO="${DATASET_REPO:-inference-optimization/Qwen3.5-9B-responses}"
DATASET_FILE="${DATASET_FILE:-gsm8k.jsonl}"

# MTP training should use data regenerated by the verifier model. When DATA_PATH is
# empty, this script downloads DATASET_FILE from DATASET_REPO before preprocessing.
OUTPUT_DIR="${OUTPUT_DIR:-./output/mtp}"
DATASET_DIR="${DATASET_DIR:-$OUTPUT_DIR/dataset}"
CHECKPOINT_DIR="${CHECKPOINT_DIR:-$OUTPUT_DIR/checkpoints}"
STITCHED_DIR="${STITCHED_DIR:-$OUTPUT_DIR/stitched}"

# ============ Training knobs ============
MAX_SAMPLES="${MAX_SAMPLES:-5000}"
SEQ_LENGTH="${SEQ_LENGTH:-8192}"
EPOCHS="${EPOCHS:-3}"
LR="${LR:-1e-4}"
NUM_SPECULATIVE_STEPS="${NUM_SPECULATIVE_STEPS:-3}"
STEP_WEIGHT_BETA="${STEP_WEIGHT_BETA:-0.6}"
TARGET_LAYER_IDS="${TARGET_LAYER_IDS:-32}"
FROM_PRETRAINED="${FROM_PRETRAINED:-}"
ON_GENERATE="${ON_GENERATE:-delete}"
HIDDEN_STATES_PATH="${HIDDEN_STATES_PATH:-}"
SAVE_BEST="${SAVE_BEST:-1}"
TRUST_REMOTE_CODE="${TRUST_REMOTE_CODE:-0}"

# ============ Runtime knobs ============
VLLM_PORT="${VLLM_PORT:-8000}"
VLLM_ENDPOINT="${VLLM_ENDPOINT:-http://localhost:${VLLM_PORT}/v1}"
VLLM_HEALTH_URL="${VLLM_HEALTH_URL:-http://localhost:${VLLM_PORT}/health}"
VLLM_GPUS="${VLLM_GPUS:-0}"
TRAIN_GPUS="${TRAIN_GPUS:-1}"
NUM_TRAIN_GPUS="${NUM_TRAIN_GPUS:-1}"
VLLM_DATA_PARALLEL_SIZE="${VLLM_DATA_PARALLEL_SIZE:-}"
VLLM_TENSOR_PARALLEL_SIZE="${VLLM_TENSOR_PARALLEL_SIZE:-}"
VLLM_GPU_MEMORY_UTILIZATION="${VLLM_GPU_MEMORY_UTILIZATION:-}"
VLLM_MAX_MODEL_LEN="${VLLM_MAX_MODEL_LEN:-}"
VLLM_ENFORCE_EAGER="${VLLM_ENFORCE_EAGER:-0}"
VLLM_EXTRA_ARGS="${VLLM_EXTRA_ARGS:-}"

# Set these to 0 when those stages are managed outside this script.
PREPARE_DATA="${PREPARE_DATA:-1}"
LAUNCH_VLLM="${LAUNCH_VLLM:-1}"
STITCH_MTP="${STITCH_MTP:-1}"

read -r -a TARGET_LAYER_ARGS <<< "$TARGET_LAYER_IDS"

download_dataset() {
    if [[ -n "$DATA_PATH" ]]; then
        return
    fi

    mkdir -p "$DATASET_DIR"
    hf download "$DATASET_REPO" "$DATASET_FILE" \
        --repo-type dataset \
        --local-dir "$DATASET_DIR"
    DATA_PATH="$DATASET_DIR/$DATASET_FILE"
}

prepare_data() {
    echo "=== Step 1: Preparing data ==="
    download_dataset

    prepare_args=(
        scripts/prepare_data.py
        --model "$MODEL"
        --data "$DATA_PATH"
        --output "$OUTPUT_DIR"
        --seq-length "$SEQ_LENGTH"
    )
    if [[ -n "$MAX_SAMPLES" ]]; then
        prepare_args+=(--max-samples "$MAX_SAMPLES")
    fi
    if [[ "$TRUST_REMOTE_CODE" == "1" ]]; then
        prepare_args+=(--trust-remote-code)
    fi

    python "${prepare_args[@]}"
}

launch_vllm() {
    echo "=== Step 2: Launching vLLM hidden-state server ==="

    vllm_args=(--port "$VLLM_PORT")
    if [[ -n "$VLLM_DATA_PARALLEL_SIZE" ]]; then
        vllm_args+=(--data-parallel-size "$VLLM_DATA_PARALLEL_SIZE")
    fi
    if [[ -n "$VLLM_TENSOR_PARALLEL_SIZE" ]]; then
        vllm_args+=(--tensor-parallel-size "$VLLM_TENSOR_PARALLEL_SIZE")
    fi
    if [[ -n "$VLLM_GPU_MEMORY_UTILIZATION" ]]; then
        vllm_args+=(--gpu-memory-utilization "$VLLM_GPU_MEMORY_UTILIZATION")
    fi
    if [[ -n "$VLLM_MAX_MODEL_LEN" ]]; then
        vllm_args+=(--max-model-len "$VLLM_MAX_MODEL_LEN")
    fi
    if [[ "$VLLM_ENFORCE_EAGER" == "1" ]]; then
        vllm_args+=(--enforce-eager)
    fi
    if [[ -n "$VLLM_EXTRA_ARGS" ]]; then
        read -r -a extra_vllm_args <<< "$VLLM_EXTRA_ARGS"
        vllm_args+=("${extra_vllm_args[@]}")
    fi

    launch_args=(scripts/launch_vllm.py "$MODEL")
    if [[ -n "$HIDDEN_STATES_PATH" ]]; then
        launch_args+=(--hidden-states-path "$HIDDEN_STATES_PATH")
    fi
    if [[ "$TRUST_REMOTE_CODE" == "1" ]]; then
        launch_args+=(--trust-remote-code)
    fi
    launch_args+=(--target-layer-ids "${TARGET_LAYER_ARGS[@]}")

    CUDA_VISIBLE_DEVICES="$VLLM_GPUS" python "${launch_args[@]}" \
        -- "${vllm_args[@]}" &
    VLLM_PID=$!

    echo "Waiting for vLLM at $VLLM_HEALTH_URL ..."
    until curl -sf "$VLLM_HEALTH_URL" > /dev/null 2>&1; do
        sleep 2
    done
    echo "vLLM server ready."
}

cleanup() {
    if [[ -n "${VLLM_PID:-}" ]]; then
        echo "Stopping vLLM server..."
        kill "$VLLM_PID" 2>/dev/null || true
        wait "$VLLM_PID" 2>/dev/null || true
    fi
}

train_mtp() {
    echo "=== Step 3: Training MTP ==="

    train_args=(
        scripts/train.py
        --verifier-name-or-path "$MODEL"
        --data-path "$OUTPUT_DIR"
        --vllm-endpoint "$VLLM_ENDPOINT"
        --save-path "$CHECKPOINT_DIR"
        --speculator-type mtp
        --num-speculative-steps "$NUM_SPECULATIVE_STEPS"
        --target-layer-ids "${TARGET_LAYER_ARGS[@]}"
        --step-weight-beta "$STEP_WEIGHT_BETA"
        --epochs "$EPOCHS"
        --lr "$LR"
        --total-seq-len "$SEQ_LENGTH"
        --on-missing generate
        --on-generate "$ON_GENERATE"
    )
    if [[ -n "$FROM_PRETRAINED" ]]; then
        train_args+=(--from-pretrained "$FROM_PRETRAINED")
    fi
    if [[ "$SAVE_BEST" == "1" ]]; then
        train_args+=(--save-best)
    fi
    if [[ -n "$HIDDEN_STATES_PATH" ]]; then
        train_args+=(--hidden-states-path "$HIDDEN_STATES_PATH")
    fi
    if [[ "$TRUST_REMOTE_CODE" == "1" ]]; then
        train_args+=(--trust-remote-code)
    fi

    if [[ "$NUM_TRAIN_GPUS" -gt 1 ]]; then
        CUDA_VISIBLE_DEVICES="$TRAIN_GPUS" torchrun \
            --standalone \
            --nproc_per_node "$NUM_TRAIN_GPUS" \
            "${train_args[@]}"
    else
        CUDA_VISIBLE_DEVICES="$TRAIN_GPUS" python "${train_args[@]}"
    fi
}

stitch_mtp() {
    echo "=== Step 4: Stitching MTP weights ==="

    checkpoint_to_stitch="${CHECKPOINT_TO_STITCH:-$CHECKPOINT_DIR/checkpoint_best}"
    if [[ ! -e "$checkpoint_to_stitch" ]]; then
        echo "No checkpoint found at $checkpoint_to_stitch"
        echo "Set CHECKPOINT_TO_STITCH to a checkpoint directory,"
        echo "or keep SAVE_BEST=1."
        exit 1
    fi

    python scripts/stitch_mtp.py \
        "$checkpoint_to_stitch" \
        "$MODEL" \
        --output-path "$STITCHED_DIR"
}

mkdir -p "$OUTPUT_DIR"

if [[ "$PREPARE_DATA" == "1" ]]; then
    prepare_data
else
    echo "=== Step 1: Skipping data preparation ==="
fi

if [[ "$LAUNCH_VLLM" == "1" ]]; then
    trap cleanup EXIT
    launch_vllm
else
    echo "=== Step 2: Using existing vLLM endpoint $VLLM_ENDPOINT ==="
fi

train_mtp

if [[ "$STITCH_MTP" == "1" ]]; then
    stitch_mtp
    echo "Done. Stitched checkpoint saved to $STITCHED_DIR/"
else
    echo "Done. MTP checkpoints saved to $CHECKPOINT_DIR/"
fi
