#!/bin/bash
# Detached MTP training for a ~122B verifier on Qwen-distilled ALLaVA (multimodal).
#
# Same pipeline as the 9B MTP launcher (extracts + fine-tunes the verifier's NATIVE
# mtp.* head; no separate draft, no FINETUNE_FROM). The ONLY real differences vs 9B
# are GPU layout: a 122B verifier (~244 GB in bf16) CANNOT be data-parallel'd — it
# must be TENSOR-parallel (sharded) for vLLM hidden-state generation, and the MTP
# trainer runs on the remaining GPUs.
#
# Target = Qwen3.5-122B-A10B: MoE (122B total / ~10B active, 256 experts), 48 layers,
# num_attention_heads=32, num_key_value_heads=2, hidden=3072, vocab=248320, native
# MTP head (mtp_num_hidden_layers=1), hybrid (linear DeltaNet + full attn). Confirmed
# from HF config.
#
# GPU LAYOUT (8x A800 80GB = 640 GB; defaults below):
#   verifier : vLLM TP=4 on GPUs 0-3  -> 244/4 ≈ 61 GB weights/GPU. KV is TINY here
#              (only 2 KV heads + 3/4 of layers are linear-attention), so 61 GB + a
#              few GB KV fits in 80 GB comfortably.
#   trainer  : torchrun on GPUs 4-7   -> MTP head (1 layer @ hidden 3072) + frozen
#              embed/lm_head + Adam — small.
#
#   Heads=32 -> valid VLLM_TP is {4,8} (NOT 6). Alternatives:
#     - VLLM_TP=8 VLLM_GPUS=0,1,2,3,4,5,6,7 GEN_GPU_MEM_UTIL=0.55 TRAIN_GPUS=6,7
#       (verifier 30.5 GB/GPU, very safe; trainer co-located in the freed memory).
#     - If TP=4 verifier OOMs: raise GEN_GPU_MEM_UTIL toward 0.92, lower SEQ_LENGTH,
#       or serve the verifier int8.
#
# USAGE
#   MODEL=/data/wenxuan/Qwen3.5-122B-A10B \
#   DISTILLED_ALLAVA_JSONL=/data/wenxuan/speculators/data/allava/allava_122b_distill_10k.jsonl \
#   bash examples/train/nohup_mtp_122b_allava_distilled.sh
#
# SMOKE TEST FIRST (validates TP + the MTP integration on the big model):
#   MAX_SAMPLES=50 EPOCHS=1 VALIDATE_INITIAL=0 \
#     MODEL=/data/wenxuan/Qwen3.5-122B-A10B DISTILLED_ALLAVA_JSONL=... \
#     bash examples/train/nohup_mtp_122b_allava_distilled.sh
#   tail -f run_logs/mtp_122b_*.nohup.log
#
# NOTE on data: MTP needs responses generated by THIS verifier. Distill them first
# with examples/train/distill_allava_122b.sh, then point DISTILLED_ALLAVA_JSONL here.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

STAMP="$(date +%Y%m%d_%H%M%S)"
RUN_NAME="${RUN_NAME:-mtp_122b_allava_distilled_${STAMP}}"
NOHUP_LOG_DIR="${NOHUP_LOG_DIR:-$REPO_ROOT/run_logs}"
NOHUP_LOG_PATH="${NOHUP_LOG_PATH:-$NOHUP_LOG_DIR/${RUN_NAME}.nohup.log}"
PID_PATH="${PID_PATH:-$NOHUP_LOG_DIR/${RUN_NAME}.pid}"
mkdir -p "$NOHUP_LOG_DIR"

# ---- verifier (122B) ; MUST contain native mtp.* weights ----
export MODEL="${MODEL:-/data/wenxuan/Qwen3.5-122B-A10B}"   # <-- set to your 122B path
if [ ! -d "$MODEL" ]; then
    echo "[fatal] MODEL not found: $MODEL  (set MODEL=/path/to/your/122B)"
    exit 1
fi

export ALLAVA_IMAGE_ROOT="${ALLAVA_IMAGE_ROOT:-/data/wenxuan/ALLaVA-4V}"
# Default to the 122B self-distilled data (make it with distill_allava_122b.sh).
export DISTILLED_ALLAVA_JSONL="${DISTILLED_ALLAVA_JSONL:-$REPO_ROOT/data/allava/allava_122b_distill_10k.jsonl}"
if [ ! -s "$DISTILLED_ALLAVA_JSONL" ]; then
    echo "[fatal] Distilled ALLaVA jsonl not found: $DISTILLED_ALLAVA_JSONL"
    exit 1
fi

# ---- GPU layout: verifier TP=4 (GPUs 0-3) + trainer (GPUs 4-7) ----
# heads=32 -> TP must be 4 or 8 (not 6). TP=4 = clean disjoint 4/4 split; KV is tiny
# on this model so 61 GB weights/GPU still fits. See header for the TP=8 co-loc alt.
export VLLM_GPUS="${VLLM_GPUS:-0,1,2,3}"
export VLLM_TP="${VLLM_TP:-4}"
export VLLM_DP="${VLLM_DP:-1}"
export GEN_GPU_MEM_UTIL="${GEN_GPU_MEM_UTIL:-0.90}"
export TRAIN_GPUS="${TRAIN_GPUS:-4,5,6,7}"
export NUM_TRAIN_GPUS="${NUM_TRAIN_GPUS:-4}"

# ---- MTP-specific (same as 9B) ----
export SPECULATOR_TYPE=mtp
export NUM_SPECULATIVE_STEPS="${NUM_SPECULATIVE_STEPS:-3}"
export STEP_WEIGHT_BETA="${STEP_WEIGHT_BETA:-0.6}"
export MTP_SELF_FORCING_P="${MTP_SELF_FORCING_P:-0.0}"
export MTP_VAL_SELF_FORCING_P="${MTP_VAL_SELF_FORCING_P:-$MTP_SELF_FORCING_P}"
export FINETUNE_FROM=""        # MTP extracts the head from MODEL itself
export DRAFT_VOCAB_SIZE=""     # full vocab

# ---- data (same contract as the distilled launcher) ----
export USE_ALLAVA=0
export USE_MMSTAR=0
export DATASET="$DISTILLED_ALLAVA_JSONL"
export MEDIA_ROOT="$ALLAVA_IMAGE_ROOT"
export OUTPUT_DIR="${OUTPUT_DIR:-./output/mtp_122b_mm_distilled}"
export SAVE_PATH="${SAVE_PATH:-./output/mtp_122b_mm_distilled/${RUN_NAME}/checkpoints}"

# ---- training knobs ----
export MAX_SAMPLES="${MAX_SAMPLES:-10000}"
export EPOCHS="${EPOCHS:-10}"
export CHECKPOINT_FREQ="${CHECKPOINT_FREQ:-1}"
export LR="${LR:-3e-5}"
export HIDDEN_STATES_DTYPE="${HIDDEN_STATES_DTYPE:-bfloat16}"   # MTP must be bf16 (fp32 breaks the lm_head)
export SEQ_LENGTH="${SEQ_LENGTH:-4096}"
export PREPROCESS_SEQ_LENGTH="${PREPROCESS_SEQ_LENGTH:-3584}"
export NO_RESUME_FROM_CHECKPOINT="${NO_RESUME_FROM_CHECKPOINT:-1}"
export VALIDATE_INITIAL="${VALIDATE_INITIAL:-1}"

export LOGGER="${LOGGER:-wandb}"
export WANDB_BASE_URL="${WANDB_BASE_URL:-http://10.155.156.175:38080}"
export WANDB_PROJECT="${WANDB_PROJECT:-speculators}"
export RUN_NAME
export LOG_TO_FILE=0

echo "Starting detached 122B MTP training:"
echo "  run_name:    $RUN_NAME"
echo "  verifier:    $MODEL   (must contain native mtp.* weights)"
echo "  vLLM:        TP=$VLLM_TP DP=$VLLM_DP on GPUs [$VLLM_GPUS]  (mem_util=$GEN_GPU_MEM_UTIL)"
echo "  trainer:     $NUM_TRAIN_GPUS GPUs [$TRAIN_GPUS]"
echo "  dataset:     $DATASET"
echo "  save_path:   $SAVE_PATH"
echo "  spec_steps:  $NUM_SPECULATIVE_STEPS   step_weight_beta=$STEP_WEIGHT_BETA"
echo "  self_force:  train=$MTP_SELF_FORCING_P   val=$MTP_VAL_SELF_FORCING_P"
echo "  epochs:      $EPOCHS   lr=$LR   max_samples=$MAX_SAMPLES   seq_len=$SEQ_LENGTH"
echo "  log:         $NOHUP_LOG_PATH"

nohup bash examples/train/dflash_qwen3.5_9b_multimodal_online.sh \
    > "$NOHUP_LOG_PATH" 2>&1 &
PID=$!
echo "$PID" > "$PID_PATH"
echo "Started PID $PID  (pid file: $PID_PATH)"
echo "Follow log:  tail -f $NOHUP_LOG_PATH"
